---

   - name: install libfontconfig1
     ansible.builtin.apt:
       name: libfontconfig1
       update_cache: yes
       state: latest

   - name: copy grafana-enterprise_10.0.3_amd64.deb
     ansible.builtin.get_url:
       url: https://dl.grafana.com/oss/release/grafana_12.0.1_amd64.deb
       dest: /tmp/grafana_12.0.1_amd64.deb


   - name: install grafana
     ansible.builtin.apt:
       deb: "/tmp/grafana_12.0.1_amd64.deb"
    # notify: start grafana-server
     
   - name: install plugin
     shell: |
       grafana-cli plugins install alexanderzobnin-zabbix-app
       
   - name: restart grafana
     systemd:
       name: grafana-server
       enabled: yes
       state: restarted

