--- 
    - name: Загрузка Zabbix репозитория
#      shell: wget https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.0-4+ubuntu22.04_all.deb
      shell: wget https://repo.zabbix.com/zabbix/7.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest_7.0+ubuntu22.04_all.deb
      args:
        chdir: /tmp

    - name: Установка Zabbix репозитория
#      shell: dpkg -i zabbix-release_6.0-4+ubuntu22.04_all.deb
      shell: dpkg -i zabbix-release_latest_7.0+ubuntu22.04_all.deb
      args:
        chdir: /tmp

    - name: Обновление пакетов
      apt:
        update_cache: yes
    - name: Установка zabbix_agent
      apt:
        name:
          - zabbix-agent
        state: present

#    - name: Создание директории для логов Zabbix Agent
#      command: mkdir -p /var/log/zabbix/
#      become_user: root

#    - name: Установка прав на директорию логов Zabbix Agent
#      command: chown zabbix /var/log/zabbix/
#      become_user: root

    - name: Копирование конфигурационного файла Zabbix Agent
      template:
        src: ./zabbix_agentd.conf.j2
        dest: /etc/zabbix/zabbix_agentd.conf

    - name: добавляем zabbix-agent в автозагрузку
      systemd:
        name: zabbix-agent
        enabled: true

    - name: restart zabbix-agent
      systemd:
        name: zabbix-agent
        state: restarted
