--- 
    - name: Загрузка Zabbix репозитория
#      shell: wget https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.0-4+ubuntu22.04_all.deb
      shell: wget https://repo.zabbix.com/zabbix/7.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest_7.0+ubuntu22.04_all.deb
      args:
        chdir: /tmp

    - name: Установка Zabbix репозитория
 #     shell: dpkg -i zabbix-release_6.0-4+ubuntu22.04_all.deb
      shell: dpkg -i zabbix-release_latest_7.0+ubuntu22.04_all.deb
      args:
        chdir: /tmp

    - name: Обновление пакетов
      apt:
        update_cache: yes

    - name: Установка необходимых пакетов Zabbix
      apt:
        name:
           
          - apache2
          - postgresql
          - zabbix-server-pgsql
           
          - zabbix-frontend-php
          - php8.1-pgsql
          - zabbix-apache-conf
          - zabbix-sql-scripts
          - zabbix-agent
        state: present

    - name: Создание пользователя PostgreSQL для Zabbix
      expect:
        command: sudo -u postgres createuser --pwprompt zabbix
        responses:
          (?i).*(Enter password for new role)(.*):
           - '{{ pass_zabbixdb }}'
          (?i).*(Enter it again)(.*):
           - '{{ pass_zabbixdb }}'

    - name: Создание базы данных PostgreSQL для Zabbix
      shell: >
        sudo -u postgres createdb -O zabbix zabbix

    - name: Импортируеv начальную схему и данные
      shell:
#        zcat /usr/share/zabbix-sql-scripts/postgresql/server.sql.gz | sudo -u zabbix psql zabbix
        zcat /usr/share/zabbix-sql-scripts/postgresql/server.sql.gz | sudo -u zabbix psql zabbix

    - name: Настройка DBPassword в конфигурационном файле Zabbix
      lineinfile:
        path: /etc/zabbix/zabbix_server.conf
        regexp: '^DBPassword='
        line: 'DBPassword=zabbix'
    
    - name: добавляем zabbix в автозагрузку
      systemd:
        name: zabbix
        enabled: true
        
    - name: restart zabbix
      systemd:
        name: zabbix-server
        state: started
        
    - name: Перезапуск служб Zabbix

      systemd:
        name: "{{ item }}"
        state: restarted
        enabled: yes

      loop:
         
#        - zabbix-server
        - zabbix-agent
        - apache2
